Repository Butlers-Team/ticat-client, pull requests merged in 2023-09, with the labels that each got.

#100 feat: Oauth 닉네임 디코딩 추가 / 디자인 수정 사항 반영
  src/api/axiosInstance.ts
  src/components/review/blog-reviews/BlogReviews.tsx
  src/components/signin/OauthCallback.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS

#104 fix : 내 위치에서 검색 + 검색 초기화 버튼 로직 분리 및 수정
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/store/mapListStore.ts
  src/types/api/weather.ts
Labels: 🐞 BugFix, 🔥 Feature, 🛠 Refector

#103 fix: 모바일 카카오톡 인앱 브라우저 주소표시줄 스크롤 시 버그 수정
  public/index.html
  src/App.tsx
  src/pages/FestivalListPage.tsx
  src/styles/GlobalStyles.tsx
Labels: 🐞 BugFix, 🛠 Refector

#105 fix : 토큰인증 안됐을 시, 로그인페이지로 라우팅
  src/Router.tsx
  src/api/recent.ts
  src/components/calendar/ReactCalendar.tsx
  src/components/detail/FestivalCover.tsx
  src/pages/CalendarPage.tsx
  src/pages/DetailPage.tsx
Labels: 🐞 BugFix, 🔥 Feature

#106 feat : 캘린더 일정 삭제 기능 구현
  src/api/addcalendar.ts
  src/api/calendar.ts
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/CalendarFestval.tsx
  src/pages/CalendarPage.tsx
  src/pages/DetailPage.tsx
Labels: 🐞 BugFix, 🔥 Feature, 🛠 Refector

#107 fix: 실시간으로 데이터가 반영되지 않는 버그 수정
  src/components/myinfo/RecentList.tsx
  src/components/stamp/StampTicket.tsx
  src/pages/FestivalListPage.tsx
  src/pages/ProfileUpdatePage.tsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#108 refactor : 캘린더 토요일 일요일 날짜 색 변경
  src/components/calendar/CalendarFestval.tsx
  src/components/calendar/ReactCalendar.tsx
  src/pages/CalendarPage.tsx
Labels: 🐞 BugFix, 🎨 HTML&CSS

#110 refactor : 축제 진행 상태에 따라 캘린더 추가 조건 추가 및 수정
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/detail/FestivalCover.tsx
Labels: 🛠 Refector

#109 feat: 현재 위치에서 해당하는 축제 조회하고 스탬프 찍기
  src/api/stamp.ts
  src/components/Button.tsx
  src/components/stamp/StampLocationCheck.tsx
  src/components/stamp/StampTicket.tsx
  src/components/stamp/TicketStamping.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
  src/types/api/stamp.ts
Labels: 📬 API, 🐞 BugFix, 🔥 Feature

#113 feat: 티켓 스탬프 캘린더 구현
  src/components/festival/Festival.tsx
  src/components/myinfo/RecentList.tsx
  src/components/myinfo/RecentListItem.tsx
  src/components/stamp/StampCalendar.tsx
  src/components/stamp/StampTicket.tsx
  src/components/stamp/StampToggle.tsx
  src/components/stamp/TicketStamping.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
  src/utils/formatDate.ts
Labels: 🐞 BugFix, 🔥 Feature

#112 fix: 디자인 수정 사항 반영 & 인스턴스 수정
  src/api/axiosInstance.ts
  src/components/myreview/MyReviewToggle.tsx
  src/components/review/ReviewEditor.tsx
  src/components/review/comment/CommentItemContent.tsx
  src/components/review/comment/CommnetItem.tsx
  src/components/review/review-item/ReviewImage.tsx
  src/pages/SignInPage.tsx
Labels: 🎨 HTML&CSS, 🛠 Refector

#114 refacgor : 캘린더 및 디테일페이지 수정사항 반영 및 인스턴스 수정
  package-lock.json
  package.json
  src/api/calendar.ts
  src/components/Button.tsx
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/CalendarFestval.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/detail/FestivalCover.tsx
  src/pages/CalendarPage.tsx
  src/pages/DetailPage.tsx
  src/types/api/addcalendar.ts
Labels: 🐞 BugFix, 🛠 Refector

#115 style: 캘린더 토요일 글자 색상 변경
  src/components/stamp/StampCalendar.tsx
Labels: 🎨 HTML&CSS

#117 fix: 새로운 리뷰댓글 마이페이지 렌더링 안되는 현상 & 디자인 수정
  src/components/myreview/comments/MyCommentList.tsx
  src/components/myreview/reviews/MyReviewList.tsx
  src/components/review/comment/CommentItemContent.tsx
  src/components/review/review-item/ReviewItem.tsx
  src/components/review/review-item/ReviewItemContent.tsx
  src/hooks/query/useCreateComment.ts
  src/hooks/query/useCreateReview.ts
Labels: 🐞 BugFix, 🎨 HTML&CSS

#118 fix : 캘린더 및 지도 파트 css 디자인 수정 및 반응형 최적화 + 리스트 접기기능 추가
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/CalendarFestval.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/components/maplist/OptionButton.tsx
  src/hooks/useCustomToast.tsx
  src/pages/CalendarPage.tsx
  src/pages/MapListPage.tsx
  src/store/mapListStore.ts
  src/styles/GlobalStyles.tsx
Labels: 🐞 BugFix, 🎨 HTML&CSS, 🛠 Refector

#119 feat : 캘린더 리스트 더보기 버튼 통해 무한스크롤
  src/api/axiosInstance.ts
  src/api/calendar.ts
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/CalendarFestval.tsx
  src/pages/CalendarPage.tsx
Labels: 🐞 BugFix, 🔥 Feature, 🛠 Refector
