Repository Butlers-Team/ticat-client, pull requests merged in 2023-06, with the labels that each got.

#5 fix: 초기세팅 파일 수정
  .eslintrc.json
  public/index.html
  public/manifest.json
  src/App.tsx
  src/index.tsx
  tsconfig.json
  tsconfig.paths.json
Labels: ⚙ Setting

#6 design: 모바일 사이즈로 수정
  src/App.tsx
  src/styles/GlobalStyles.tsx
Labels: 🎨 HTML&CSS, ⚙ Setting

#14 feat: 로그인 페이지 기본 레이아웃
  src/components/sign-in/OauthButton.tsx
  src/components/sign-in/SignIn.tsx
  src/pages/SignInPage.tsx
  src/styles/OauthColor.ts
Labels: 🔥 Feature

#18 feat: 스탬프 위치 확인 페이지 구현
  .github/PULL_REQUEST_TEMPLATE.md
  src/App.tsx
  src/Router.tsx
  src/components/Button.tsx
  src/pages/StampCheck.tsx
  src/pages/StampValid.tsx
Labels: 🐞 BugFix, 🔥 Feature

#19 feat: 스탬프 티켓 리스트 페이지 구현
  public/assets/images/ticat-logo-icon-black.png
  public/assets/images/ticat-logo-icon-gray.png
  src/Router.tsx
  src/components/stamp/StampTicket.tsx
  src/pages/StampList.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS
