Repository Butlers-Team/ticat-client, pull requests merged in 2023-07, with the labels that each got.

#22 feat: tab-nav bar 컴포넌트 구현완료 Closes Butlers-Team#20
  src/components/main/FestivalSlider.tsx
  src/layout/tab-nav/index.tsx
  src/styles/GlobalStyles.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS

#24 feat: main-page 컴포넌트 구현 및 전역스타일링 수정
  public/index.html
  src/Router.tsx
  src/components/main/CategoryIcon.tsx
  src/components/main/FestivalSlider.tsx
  src/components/main/MainSlider.tsx
  src/components/main/MyInfoButton.tsx
  src/layout/tab-nav/index.tsx
  src/pages/MainPage.tsx
  src/styles/GlobalStyles.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS

#23 feat: 스탬프 토글 버튼 구현
  src/components/Button.tsx
  src/components/stamp/StampCalendar.tsx
  src/components/stamp/StampTicket.tsx
  src/components/stamp/StampToggle.tsx
  src/pages/StampList.tsx
  src/pages/StampValid.tsx
  src/styles/GlobalStyles.tsx
Labels: 🐞 BugFix, 🔥 Feature

#26 fix: 브라우저 주소표시줄 가려짐 현상 수정
  src/App.tsx
  src/layout/index.tsx
  src/layout/main/index.tsx
  src/styles/GlobalStyles.tsx
Labels: 🐞 BugFix, 🔥 Feature

#29 design: toggle 여백 및 위치 css 수정
  src/pages/StampList.tsx
Labels: 🎨 HTML&CSS

#32 feat: 축제 리스트 instance response type 지정
  src/api/catergory.ts
  src/types/api/catergory.ts
  src/types/api/index.ts
Labels: 🔥 Feature

#33 feat: 회원가입페이지 기본 레이아웃 구성
  src/Router.tsx
  src/components/Button.tsx
  src/components/sign-in/SignIn.tsx
  src/components/sign-up/SignUp.tsx
  src/components/sign-up/SignupInputForm.tsx
  src/pages/SignUpPage.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS

#36 feat: 회원가입 환영 페이지
  public/assets/images/symbol-ticat.png
  public/assets/images/symbol-ticat1.png
  public/assets/images/ticat-logo-icon-01.png
  public/assets/images/ticat-logo-icon-02.png
  src/Router.tsx
  src/components/Wellcome.tsx
  src/layout/index.tsx
  src/pages/WellcomePage.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS

#38 feat : main-page 캐러셀 배너 구현완료 (swiper)
  package-lock.json
  package.json
  src/components/main/CategoryIcon.tsx
  src/components/main/MainSlider.tsx
  src/components/main/RecommendFestival.tsx
  src/pages/MainPage.tsx
  src/types/swiper/swiperOptions.ts
Labels: 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#42 feat : 축제 상세 페이지 레이아웃 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/components/Button.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/detail/FestivalCover.tsx
  src/components/detail/FestivalInfo.tsx
  src/components/detail/FestivalLocation.tsx
  src/components/detail/Recommend.tsx
  src/components/main/MainSlider.tsx
  src/layout/tab-nav/index.tsx
  src/pages/CalendarPage.tsx
  src/pages/DetailPage.tsx
Labels: 🔥 Feature, 🎨 HTML&CSS

#45 feat: 축제 리스트 카테고리 layout 구현
  package-lock.json
  package.json
  src/Router.tsx
  src/components/festival/CatergoryTabNav.tsx
  src/components/festival/Festival.tsx
  src/components/festival/FestivalList.tsx
  src/components/main/MainSlider.tsx
  src/pages/FestivalListPage.tsx
  src/types/api/catergory.ts
  src/utils/formatDate.ts
  tsconfig.paths.json
Labels: 🔥 Feature, 🎨 HTML&CSS

#44 feat: 차크라UI 설치 및 기본설정
  package-lock.json
  package.json
  src/hooks/useCustomToast.tsx
  src/index.tsx
Labels: ⚙ Setting

#48 feat: 축제리스트 무한스크롤 구현
  package-lock.json
  package.json
  src/api/category.ts
  src/api/catergory.ts
  src/api/index.ts
  src/components/festival/CategoryTabNav.tsx
  src/components/festival/Festival.tsx
  src/components/festival/FestivalList.tsx
  src/components/main/MainSlider.tsx
  src/pages/FestivalListPage.tsx
  src/types/api/category.ts
  src/types/api/index.ts
Labels: 🐞 BugFix, 🔥 Feature

#50 feat : 공용 pop-up 모달 컴포넌트 구현 및 추천축제 배너 공용컴포넌트 Refector
  public/assets/images/ticat-cover-image.png
  src/components/Popup.tsx
  src/components/RecommendFestival.tsx
  src/components/main/MainSlider.tsx
  src/components/main/MyInfoButton.tsx
  src/components/main/RecommendFestival.tsx
  src/index.tsx
  src/layout/tab-nav/index.tsx
  src/pages/MainPage.tsx
  src/styles/GlobalStyles.tsx
  src/types/swiper/swiperOptions.ts
Labels: 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#52 축제 상세페이지 카카오맵 축제위치 마커찍기
  public/index.html
  src/Router.tsx
  src/api/detail.ts
  src/api/index.ts
  src/components/Button.tsx
  src/components/RecommendFestival.tsx
  src/components/detail/FestivalCover.tsx
  src/components/detail/FestivalInfo.tsx
  src/components/detail/FestivalLocation.tsx
  src/components/detail/Recommend.tsx
  src/index.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/styles/GlobalStyles.tsx
  src/types/api/detail.ts
Labels: 📬 API, 🔥 Feature

#53 rename: 파일 분리 후, 파일 이름 변경
  src/Router.tsx
  src/components/RecommendFestival.tsx
  src/components/festival/Festival.tsx
  src/components/main/MainSlider.tsx
  src/pages/AreaFilterPage.tsx
  src/pages/FestivalListPage.tsx
  src/pages/MainPage.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
  src/types/api/category.ts
  src/types/api/festival.ts
  src/types/api/index.ts
Labels: 🐞 BugFix, 🛠 Refector

#55 feat : map-list category 버튼 구현 및 기본 레이아웃 구축 + utils 함수추가
  src/Router.tsx
  src/components/Button.tsx
  src/components/Popup.tsx
  src/components/RecommendFestival.tsx
  src/components/main/MainSlider.tsx
  src/components/map-list/FastivalList.tsx
  src/components/map-list/MapScreen.tsx
  src/components/map-list/OptionButton.tsx
  src/hooks/.gitkeep
  src/layout/index.tsx
  src/layout/tab-nav/index.tsx
  src/pages/MainPage.tsx
  src/pages/MapListPage.tsx
  src/utils/.gitkeep
  src/utils/truncatedText.ts
Labels: 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#56 feat : 로컬 로그인/회원가입 , Oauth / ChakraUI 세팅 수정
  .eslintrc.json
  src/Router.tsx
  src/api/auth/authApi.ts
  src/api/auth/index.ts
  src/api/auth/signIn.ts
  src/api/auth/signUp.ts
  src/api/axiosInstance.ts
  src/api/index.ts
  src/components/interest/Interest.tsx
  src/components/signin/OauthButton.tsx
  src/components/signin/OauthCallback.tsx
  src/components/signin/SignIn.tsx
  src/components/signup/SignUp.tsx
  src/components/signup/SignupInputForm.tsx
  src/hooks/query/index.ts
  src/hooks/query/useSignIn.ts
  src/hooks/query/useSignUp.ts
  src/hooks/useCustomToast.tsx
  src/index.tsx
  src/layout/index.tsx
  src/pages/InterestPage.tsx
  src/pages/OauthCallbackPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/provider/MyChakraProvier.tsx
  src/provider/MyReactQueryProvider.tsx
  src/provider/index.tsx
  src/store/authStore.ts
  src/styles/GlobalStyles.tsx
  src/types/auth/index.ts
  src/types/auth/signIn.ts
  src/types/auth/signUp.ts
  tsconfig.paths.json
Labels: 📬 API, 🔥 Feature

#59 feat: 닉네임, 관심사 등록 페이지 구현
  src/api/auth/authApi.ts
  src/api/axiosInstance.ts
  src/api/interest.ts
  src/components/Wellcome.tsx
  src/components/interest/Category.tsx
  src/components/interest/Interest.tsx
  src/components/interest/NickNameInput.tsx
  src/components/signin/SignIn.tsx
  src/components/signup/SignUp.tsx
  src/hooks/query/index.ts
  src/hooks/query/useResisterInterest.ts
  src/hooks/query/useSignIn.ts
  src/hooks/query/useSignUp.ts
  src/layout/index.tsx
  src/pages/InterestPage.tsx
  src/store/authStore.ts
  src/types/api/index.ts
  src/types/api/interest.ts
  src/utils/categories.ts
Labels: 📬 API, 🔥 Feature, 🎨 HTML&CSS

#60 feat : 축제 상세페이지 동일한 카테고리 추천 구현
  package-lock.json
  src/api/recommend.ts
  src/components/detail/FestivalInfo.tsx
  src/components/detail/Recommend.tsx
  src/components/signin/OauthButton.tsx
  src/pages/DetailPage.tsx
  src/types/api/detail.ts
  src/types/api/recommend.ts
Labels: 📬 API, 🔥 Feature, 🎨 HTML&CSS

#62 refactor: 토큰 갱신 로직 수정 / 카테고리 버튼 컴포넌트 분리
  src/api/auth/authApi.ts
  src/api/auth/signIn.ts
  src/api/auth/signUp.ts
  src/api/axiosInstance.ts
  src/components/CommonCategoryButton.tsx
  src/components/CommonCategoryList.tsx
  src/components/CommonCatogoryItem.tsx
  src/components/interest/Category.tsx
  src/components/interest/Interest.tsx
  src/components/signup/SignupInputForm.tsx
  src/store/authStore.ts
Labels: 🔥 Feature, 🛠 Refector

#63 refactor: 축제 지역선택 리스트 리팩토링
  public/index.html
  src/components/areaFilter/AreaDropDown.tsx
  src/components/festival/Festival.tsx
  src/pages/AreaFilterPage.tsx
  src/pages/FestivalListPage.tsx
  src/utils/address.ts
Labels: 🐞 BugFix, 🔥 Feature, 🛠 Refector

#64 feat : 축제 상세페이지 클립보드복사/축제홈페이지이동/좋아요기능 구현 및 피드백 수정
  src/api/festivalliked.ts
  src/components/detail/FestivalCover.tsx
  src/components/detail/FestivalInfo.tsx
  src/components/detail/Recommend.tsx
  src/types/api/detail.ts
  src/types/api/recommend.ts
  src/utils/shareKakao.ts
Labels: 📬 API, 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#68 feat : 축제 상세페이지 지역 날씨정보 및 아이콘 구현
  src/api/axiosInstance.ts
  src/api/detail.ts
  src/api/recommend.ts
  src/api/weather.ts
  src/components/RecommendFestival.tsx
  src/components/WeatherIcon.tsx
  src/components/detail/FestivalCover.tsx
  src/components/detail/FestivalInfo.tsx
  src/components/detail/Recommend.tsx
  src/types/api/weather.ts
Labels: 📬 API, 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#69 feat : 축제 상세페이지 내 경로찾기 구현 및 상세페이지 리팩토링 #68
  src/api/detail.ts
  src/api/festivalliked.ts
  src/components/detail/FestivalCover.tsx
  src/components/detail/FestivalLocation.tsx
Labels: 🐞 BugFix, 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#73 feat: map-list , main-page API 데이터 연결
  package-lock.json
  package.json
  public/assets/images/default-profile-image.png
  src/api/mainfastival.ts
  src/api/mapfastival.ts
  src/components/LodingIcon.tsx
  src/components/RecommendFestival.tsx
  src/components/detail/FestivalInfo.tsx
  src/components/festival/CategoryTabNav.tsx
  src/components/main/CategoryIcon.tsx
  src/components/main/MainSlider.tsx
  src/components/main/MyInfoButton.tsx
  src/components/map-list/FastivalList.tsx
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/components/maplist/OptionButton.tsx
  src/layout/index.tsx
  src/pages/FestivalListPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapListPage.tsx
  src/store/.gitkeep
  src/store/mapListStore.ts
  src/styles/GlobalStyles.tsx
  src/types/api/mainfastival.ts
  src/types/api/mapfastival.ts
  src/types/festival/festivalInfo.ts
Labels: 📬 API, 🐞 BugFix, 🔥 Feature, 🛠 Refector

#76 bugfix : 날씨 위치정보 변수 위치 변경
  src/components/main/MyInfoButton.tsx
Labels: 🐞 BugFix
