Repository Butlers-Team/ticat-client, pull requests merged in 2023-08, with the labels that each got.

#81 feat: 토큰 만료 시간 저장
  src/api/auth/index.ts
  src/api/auth/refresh.ts
  src/api/auth/signIn.ts
  src/api/axiosInstance.ts
  src/components/CommonCategoryButton.tsx
  src/components/CommonCategoryList.tsx
  src/components/interest/Category.tsx
  src/hooks/query/useSignIn.ts
  src/pages/MyPage.tsx
  src/store/useExpStore.ts
  src/store/useMemberStore.ts
  src/types/auth/index.ts
  src/types/auth/refresh.ts
  src/types/auth/signIn.ts
  src/utils/dateToSeconds.ts
Labels: 📬 API, 🔥 Feature

#85 feat : 위치정보 전역관리 + 축제 status 표기 추가 + setting page 로그아웃 구현
  src/App.tsx
  src/components/festival/Festival.tsx
  src/components/main/MyInfoButton.tsx
  src/components/mysetting/MySetting.tsx
  src/data/settingData.ts
  src/pages/MainPage.tsx
  src/pages/SettingPage.tsx
  src/store/userLocation.ts
Labels: 📬 API, 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#86 대소문자 구분안되는 파일 삭제
  src/store/CategoryTabStore.ts
Labels: 🐞 BugFix

#88 feat: 마이페이지 프로필 정보 수정 페이지 구현
  src/Router.tsx
  src/api/myinfo.ts
  src/components/CommonCategoryButton.tsx
  src/components/main/MyInfoButton.tsx
  src/components/myinfo/MyInfoDescription.tsx
  src/components/profile/ProfileImageUpdate.tsx
  src/components/profile/ProfileInfoNameUpdate.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileUpdatePage.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
  src/store/.gitkeep
  src/types/api/myinfo.ts
Labels: 📬 API, 🔥 Feature

#91 feat : map list 추가 버튼 기능 구현 및 마커 디자인 변경 + 사용자 위치정보 초기값 변경
  public/assets/images/ticat-logo-icon-undefined.png
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/components/maplist/OptionButton.tsx
  src/pages/MapListPage.tsx
  src/store/mapListStore.ts
  src/store/userLocation.ts
  src/types/api/mapfastival.ts
Labels: 🐞 BugFix, 🔥 Feature, 🎨 HTML&CSS, 🛠 Refector

#94 fix: 마이페이지 및 축제리스트, 스탬프 페이지 전체적인 버그 및 수정
  public/assets/images/google-logo.png
  public/assets/images/kakao-logo.png
  public/assets/images/naver-logo.png
  src/Router.tsx
  src/api/myinfo.ts
  src/api/stamp.ts
  src/components/Button.tsx
  src/components/area-filter/AreaDropDown.tsx
  src/components/festival/CategoryTabNav.tsx
  src/components/interest/NickNameInput.tsx
  src/components/main/CategoryIcon.tsx
  src/components/myinfo/MyInfoDescription.tsx
  src/components/myinfo/RecentList.tsx
  src/components/profile/ProfileImageUpdate.tsx
  src/components/stamp/StampDate.tsx
  src/components/stamp/StampLocationCheck.tsx
  src/components/stamp/StampTicket.tsx
  src/components/stamp/TicketStamping.tsx
  src/hooks/query/useFetchCategories.ts
  src/pages/AreaFilterPage.tsx
  src/pages/FestivalListPage.tsx
  src/pages/MyPage.tsx
  src/pages/ProfileUpdatePage.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
  src/store/useAreaFilterStore.ts
  src/store/useCategoryTabStore.ts
  src/types/api/myinfo.ts
  src/types/api/stamp.ts
  src/utils/validateNickname.ts
Labels: 📬 API, 🐞 BugFix, 🔥 Feature

#95 Fe feat/map list/#87
  src/api/comment.ts
  src/api/mapfastival.ts
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/components/maplist/OptionButton.tsx
  src/components/review/blog-reviews/BlogSwiper.tsx
  src/store/mapListStore.ts
  src/store/userLocation.ts
  src/styles/GlobalStyles.tsx
  src/types/swiper/swiperOptions.ts
Labels: 📬 API, 🔥 Feature, 🛠 Refector

#96 bug: 스탬프 화살표 이전달로 넘어갈 때 false 처리되는 버그 수정
  src/components/festival/CategoryTabNav.tsx
  src/pages/StampListPage.tsx
Labels: 🐞 BugFix, 🔥 Feature

#98 fix: 리뷰댓글 로직 및 ui 수정 / 블로그 게시글 fetch 수정
  src/components/interest/Interest.tsx
  src/components/maplist/MapScreen.tsx
  src/components/myreview/MyReview.tsx
  src/components/profile/ProfileImageUpdate.tsx
  src/components/review/ReviewEditor.tsx
  src/components/review/comment/CommentItemHeader.tsx
  src/components/review/comment/CommnetItem.tsx
  src/components/review/review-item/ReviewItem.tsx
  src/components/review/review-item/ReviewItemHeader.tsx
  src/hooks/query/useFetchBlogPosts.ts
  src/pages/FestivalListPage.tsx
  src/pages/StampValidPage.tsx
  src/utils/createFormData.ts
Labels: 🐞 BugFix, 🎨 HTML&CSS, 🛠 Refector
