Repository Butlers-Team/ticat-client, pull requests merged in 2023-10, with the labels that each got.

#124 refactor : 캘린더 기간설정 초기값 수정 및 쓰로우에러 핸들링
  README.md
  src/api/calendar.ts
  src/components/calendar/AddCalendarForm.tsx
  src/pages/CalendarPage.tsx
Labels: 🐞 BugFix, 🛠 Refector

#127 style : 해상도 별 css 깨짐 현상 해결 + 하단 네비게이션 index 저장방식 변경
  README.md
  src/Router.tsx
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/interest/Interest.tsx
  src/components/main/MainSlider.tsx
  src/components/mysetting/MySetting.tsx
  src/components/signin/OauthCallback.tsx
  src/hooks/query/useResisterInterest.ts
  src/hooks/query/useSignIn.ts
  src/layout/tab-nav/index.tsx
  src/pages/MapListPage.tsx
  src/types/api/weather.ts
Labels: 🎨 HTML&CSS, 🛠 Refector

#125 refactor : 서버에 삭제요청이 반영 되는 시간 기다렸다가 요청하도록 수정
  src/api/calendar.ts
  src/components/calendar/CalendarFestval.tsx
  src/pages/CalendarPage.tsx
Labels: 🐞 BugFix, 🛠 Refector

#129 dev -> main 브랜치 병합 pull requests
  README.md
  package-lock.json
  package.json
  src/Router.tsx
  src/api/axiosInstance.ts
  src/api/calendar.ts
  src/components/Button.tsx
  src/components/area-filter/AreaDropDown.tsx
  src/components/calendar/AddCalendarForm.tsx
  src/components/calendar/CalendarFestval.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/festival/Festival.tsx
  src/components/interest/Interest.tsx
  src/components/main/MainSlider.tsx
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/components/maplist/OptionButton.tsx
  src/components/myinfo/MyInfoDescription.tsx
  src/components/myinfo/RecentList.tsx
  src/components/myinfo/RecentListItem.tsx
  src/components/myreview/MyReviewToggle.tsx
  src/components/myreview/comments/MyCommentList.tsx
  src/components/myreview/reviews/MyReviewList.tsx
  src/components/mysetting/MySetting.tsx
  src/components/profile/ProfileImageUpdate.tsx
  src/components/review/ReviewEditor.tsx
  src/components/review/comment/CommentItemContent.tsx
  src/components/review/comment/CommnetItem.tsx
  src/components/review/review-item/ReviewImage.tsx
  src/components/review/review-item/ReviewItem.tsx
  src/components/review/review-item/ReviewItemContent.tsx
  src/components/review/review-item/ReviewLikes.tsx
  src/components/signin/OauthButton.tsx
  src/components/signin/OauthCallback.tsx
  src/components/signin/SignIn.tsx
  src/components/stamp/StampCalendar.tsx
  src/components/stamp/StampTicket.tsx
  src/components/stamp/StampToggle.tsx
  src/components/stamp/TicketStamping.tsx
  src/hooks/query/useCreateComment.ts
  src/hooks/query/useCreateReview.ts
  src/hooks/query/useResisterInterest.ts
  src/hooks/query/useReviewDislike.ts
  src/hooks/query/useReviewLike.ts
  src/hooks/query/useSignIn.ts
  src/hooks/useCustomToast.tsx
  src/layout/tab-nav/index.tsx
  src/pages/AreaFilterPage.tsx
  src/pages/CalendarPage.tsx
  src/pages/DetailPage.tsx
  src/pages/MapListPage.tsx
  src/pages/SignInPage.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
  src/store/mapListStore.ts
  src/store/useExpStore.ts
  src/store/useMemberStore.ts
  src/styles/GlobalStyles.tsx
  src/types/api/weather.ts
  src/utils/formatDate.ts
Labels: 🌏 Deploy

#131 style : 검색버튼 css 수정 및 메인카테고리 탭메뉴 적용 오류 수정
  src/components/main/CategoryIcon.tsx
  src/components/maplist/MapScreen.tsx
Labels: 🎨 HTML&CSS, 🛠 Refector

#132 마이페이지(회원탈퇴, 관심사 수정, 최근목록 좋아요/좋아요 취소) 기능 구현 및 스탬프 페이지 뒤로가기 버그 수정
  src/api/myinfo.ts
  src/components/main/MyInfoButton.tsx
  src/components/myinfo/RecentList.tsx
  src/components/myinfo/RecentListItem.tsx
  src/components/mysetting/MySetting.tsx
  src/hooks/query/useDeleteMember.ts
  src/hooks/query/usePostFestivalLike.ts
  src/hooks/query/usePostFestivalUnLike.ts
  src/pages/MyPage.tsx
  src/pages/ProfileUpdatePage.tsx
  src/pages/SettingPage.tsx
  src/pages/StampListPage.tsx
  src/pages/StampValidPage.tsx
Labels: 🐞 BugFix, 🔥 Feature

#133 fix: UX 문제 해결 및 리팩토링
  src/Router.tsx
  src/api/axiosInstance.ts
  src/api/blogpost.ts
  src/components/interest/Interest.tsx
  src/components/main/MainSlider.tsx
  src/components/post/PostContent.tsx
  src/components/post/PostEditDeleteButton.tsx
  src/components/post/PostHeader.tsx
  src/components/post/PostTitle.tsx
  src/components/post/blog-reviews/BlogReviews.tsx
  src/components/post/blog-reviews/BlogSwiper.tsx
  src/components/post/comments/Comment.tsx
  src/components/post/comments/CommentEditorForm.tsx
  src/components/post/comments/CommentList.tsx
  src/components/post/comments/CommnetItem.tsx
  src/components/post/comments/MyCommentList.tsx
  src/components/post/reviews/MyReview.tsx
  src/components/post/reviews/MyReviewList.tsx
  src/components/post/reviews/MyReviewToggle.tsx
  src/components/post/reviews/ReviewEditorForm.tsx
  src/components/post/reviews/ReviewHeader.tsx
  src/components/post/reviews/ReviewImage.tsx
  src/components/post/reviews/ReviewItem.tsx
  src/components/post/reviews/ReviewLikes.tsx
  src/components/post/reviews/Reviews.tsx
  src/components/post/reviews/ReviewsList.tsx
  src/components/review/comment/CommentEditDelete.tsx
  src/components/review/comment/CommentItemContent.tsx
  src/components/review/comment/CommentItemHeader.tsx
  src/components/review/review-item/ReviewEditDelete.tsx
  src/components/review/review-item/ReviewItemContent.tsx
  src/components/review/review-item/ReviewItemHeader.tsx
  src/components/review/review-item/ReviewLikes.tsx
  src/components/signin/OauthCallback.tsx
  src/hooks/query/useCreateComment.ts
  src/hooks/query/useDeleteComment.ts
  src/hooks/query/useReviewDislike.ts
  src/hooks/query/useReviewLike.ts
  src/hooks/query/useSignIn.ts
  src/hooks/useCustomToast.ts
  src/hooks/useFocusAndScroll.ts
  src/hooks/useIsSameLocation.ts
  src/pages/DetailPage.tsx
  src/pages/InterestPage.tsx
  src/pages/MyPage.tsx
  src/store/useExpStore.ts
  src/store/useMemberStore.ts
  src/store/useTokenStore.ts
  src/types/api/review-like.ts
  src/types/auth/signIn.ts
  src/utils/convertLine.ts
  src/utils/optimisticUpdateWithMutate.ts
Labels: 🐞 BugFix, 🎨 HTML&CSS, 🛠 Refector

#136 타입 호환 문제 해결
  src/components/post/reviews/ReviewLikes.tsx
  src/types/api/reviews.ts
  src/utils/optimisticUpdateWithMutate.ts
Labels: 🐞 BugFix, 🔥 Feature

#138 refactor : 캘린더 및 디테일페이지 피드백사항 수정
  src/components/Button.tsx
  src/components/calendar/CalendarFestval.tsx
  src/components/calendar/ReactCalendar.tsx
  src/components/detail/FestivalCover.tsx
  src/components/detail/FestivalLocation.tsx
  src/components/stamp/TicketStamping.tsx
  src/pages/CalendarPage.tsx
  src/types/api/calendar.ts
Labels: 🐞 BugFix, 🔥 Feature, 🛠 Refector

#139 bugfix : 과도한 요청으로인해 kakao map 렌더링 오류현상 해결 (임시)
  src/components/maplist/FastivalList.tsx
  src/components/maplist/MapScreen.tsx
  src/pages/CalendarPage.tsx
  src/pages/MapListPage.tsx
  src/store/mapListStore.ts
Labels: 🐞 BugFix
